# SoloDeck synthetic data generator
# This file was generated by ChatGPT. Run with: python solodeck_synthetic_data_generator.py
# It creates realistic mock CSVs for content creator / one-person company causal insight testing.
# For the full version used in this session, see the generated CSV files in the zip.
print("Use the bundled CSV files in solodeck_synthetic_data.zip. The full generator code is in the ChatGPT response.")
